services:
  email_processor:
    environment:
      - LLM_URL=http://host.docker.internal:11434/api
    extra_hosts:
      - "host.docker.internal:host-gateway"

  response_agent:
    environment:
      - LLM_URL=http://host.docker.internal:11434/api
    extra_hosts:
      - "host.docker.internal:host-gateway"

  summary_agent:
    environment:
      - LLM_URL=http://host.docker.internal:11434/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
