version: '3.8'

services:
  email_processor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - A2A_SERVER_PORT=8001
      - EMAIL_PROCESSOR_AGENT_PORT=8001
      - RESPONSE_AGENT_PORT=8002
      - SUMMARY_AGENT_PORT=8003
      - LLM_URL=http://localhost:11434/api/generate
      - CHROMA_PERSIST_DIR=/app/data/chroma
    volumes:
      - ./data:/app/data
      - ./output:/app/output

  response_agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - A2A_SERVER_PORT=8002
      - RESPONSE_AGENT_PORT=8002
      - EMAIL_PROCESSOR_AGENT_PORT=8001
      - LLM_URL=http://localhost:11434/api/generate
    volumes:
      - ./data:/app/data
      - ./output:/app/output

  summary_agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - A2A_SERVER_PORT=8003
      - SUMMARY_AGENT_PORT=8003
      - EMAIL_PROCESSOR_AGENT_PORT=8001
      - LLM_URL=http://localhost:11434/api/generate
    volumes:
      - ./data:/app/data
      - ./output:/app/output
